tf/app.py
import os
import logging

from logging.handlers import RotatingFileHandler

from flask import Flask, request, jsonify
from werkzeug.contrib.profiler import ProfilerMiddleware

from .filters import add_html_filters


def create_app(config):
    '''
    Create the application instance.

    :param config: The configuration object.
    '''
    app = Flask(__name__)

    config_application(app, config)
    config_error_handlers(app)
    config_extensions(app)
    config_before_handlers(app)
    config_html_filters(app)
    config_modules(app)
    config_logging(app)

    return app


def config_application(app, config):
    """Configure the application instance."""
    app.config.from_object(config)

    if app.debug and app.config['PROFILE']:
        """Watch running app's profile"""
        app.wsgi_app = ProfilerMiddleware(app.wsgi_app, restrictions=[10])


def config_error_handlers(app):
    @app.errorhandler(403)
    def forbidden(error):
        if request.is_xhr:
            return jsonify(error='403 forbidden')
        # return render_template('error.html', error=error), 403
        return '403 forbidden'

    @app.errorhandler(404)
    def page_not_found(error):
        # return render_template('404.html'), 404
        return '404 page not found'

    @app.errorhandler(405)
    def method_not_allowed(error):
        pass

    @app.errorhandler(500)
    def internal_error(error):
        pass


def config_extensions(app):
    pass


def config_before_handlers(app):
    pass


def config_html_filters(app):
    add_html_filters(app)


def config_modules(app):
    for module, url_prefix in app.config['MODULES']:
        app.register_blueprint(module, url_prefix=url_prefix)


def config_logging(app):
    formatter = logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]'
    )

    debug_log = os.path.join(app.root_path, app.config['DEBUG_LOG'])
    debug_file_handler = \
        RotatingFileHandler(debug_log,
                            maxBytes=100000,
                            backupCount=10)

    debug_file_handler.setLevel(logging.DEBUG)
    debug_file_handler.setFormatter(formatter)
    app.logger.addHandler(debug_file_handler)

    error_log = os.path.join(app.root_path, app.config['ERROR_LOG'])
    error_file_handler = \
        RotatingFileHandler(error_log,
                            maxBytes=100000,
                            backupCount=10)

    error_file_handler.setLevel(logging.ERROR)
    error_file_handler.setFormatter(formatter)
    app.logger.addHandler(error_file_handler)

tf/modules/frontend/__init__.py
# -*- coding: utf-8 -*-
from .views import bp

__all__ = ['bp']

tf/modules/frontend/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template

bp = Blueprint('frontend', __name__)


@bp.route('/')
def index():
    return render_template('frontend/index.html')


@bp.route('/events')
def events():
    return render_template('frontend/events.html')

tf/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    {% block meta %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% endblock %}

    {% block title %}<title>Thunder Fighter</title>{% endblock %}
    {# {% block favicon %}<link rel="shortcut icon" href="/static/favicon.ico">{% endblock %} #}

    {% block css %}
    <link rel="stylesheet" href="/static/plugins/foundation/css/normalize.css">
    <link rel="stylesheet" href="/static/plugins/foundation/css/foundation.min.css">
    <link rel="stylesheet" href="/static/css/tf.css">
    {% endblock %}

    {% block css_snippets %}{% endblock %}

    {% block preload_js %}
    <script src="/static/plugins/foundation/js/vendor/modernizr.js"></script>
    <script src="/static/plugins/foundation/js/vendor/jquery.js"></script>
    {% endblock %}
  </head>

  <body class="antialiased hide-extras">
    <div class="off-canvas-wrap" data-offcanvas>
      <div class="inner-wrap">

        {% include 'off_canvas_menu.html' %}
        {% include 'topbar.html' %}
        {% include 'page-header.html' %}

        <section role="main" id="main" class="scroll-container">
          {% block content %}{% endblock %}
        </section>

        {% block footer %}{% endblock %}

        <!-- close the off-canvas menu -->
        <a class="exit-off-canvas"></a>
      </div><!-- end .inner-wrap -->
    </div><!-- end .off-canvas-wrap -->

    {% block load_js %}
    <script src="/static/plugins/foundation/js/foundation.min.js"></script>
    {% endblock %}

    {% block js_snippets %}
      <script>
        $(document).foundation();
      </script>
    {% endblock %}
  </body>
</html>

tf/templates/entries/entry_list.html
<!-- ENTRY LIST -->
<ul class="entry-list">
  <li class="list-item">
    <div class="media row">
      <div class="small-1 columns"><span class="secondary label">1</span></div>
      <div class="small-11 columns">
        <p class="title"><a href="#">[NEWS]&nbsp;&nbsp;New Game Coming Soon!!!</a></p>
        <p class="date">2014-11-10</p>
      </div>
    </div>
  </li>
  <li class="list-item">
    <div class="media row">
      <div class="small-1 columns"><span class="secondary label">2</span></div>
      <div class="small-11 columns">
        <p class="title"><a href="#">[NEWS]&nbsp;&nbsp;New Game Coming Soon!!!</a></p>
        <p class="date">2014-11-10</p>
      </div>
    </div>
  </li>
  <li class="list-item">
    <div class="media row">
      <div class="small-1 columns"><span class="secondary label">3</span></div>
      <div class="small-11 columns">
        <p class="title"><a href="#">[NEWS]&nbsp;&nbsp;New Game Coming Soon!!!</a></p>
        <p class="date">2014-11-10</p>
      </div>
    </div>
  </li>
  <li class="list-item">
    <div class="media row">
      <div class="small-1 columns"><span class="secondary label">4</span></div>
      <div class="small-11 columns">
        <p class="title"><a href="#">[NEWS]&nbsp;&nbsp;New Game Coming Soon!!!</a></p>
        <p class="date">2014-11-10</p>
      </div>
    </div>
  </li>
</ul>
<!-- END ENTRY LIST -->

tf/templates/frontend/events.html
{% extends 'base.html' %}

tf/templates/frontend/index.html
{% extends 'base.html' %}

{% block content %}
<div class="section row text-center" id="footer">
&copy; Funplus
</div>
{% endblock %}

{% block preload_js %}
{{ super() }}
<script src="/static/plugins/responsiveslides.min.js"></script>
{% endblock %}

{% block js_snippets %}
{{ super()  }}

<script>
  /*$('.slides').responsiveSlides({});*/
</script>
{% endblock %}

tf/templates/off_canvas_menu.html
<nav class="tab-bar show-for-small" data-topbar>
  <section class="left-small">
    <a href="#"><img src="/static/img/logo.jpg" alt="Logo" width="100"></a>
  </section>
  <section class="right-small">
    <a class="right-off-canvas-toggle menu-icon" href="#"><span></span></a>
  </section>
</nav>

<aside class="right-off-canvas-menu">
  <ul class="off-canvas-list">
    <li><a href="{{ url_for('frontend.index') }}">Home</a></li>
    <li><a href="#">Events</a></li>
    <li><a href="#">Game Info</a></li>
    <li><a href="#">Strategies</a></li>
  </ul>
</aside>

tf/templates/page-header.html
<div class="page-header scroll-container">
  <div class="row" id="logo">
    <div class="small-8 right columns">
      <img src="/static/img/logo.png">
    </div>
  </div>

  <div class="row">
    <div class="small-10 small-centered medium-6 medium-offset-6 columns end">
      <div class="row">
        <div class="small-6 buttons columns">
          <div class="row">
<!--             <div class="small-12 columns">
              <a href="#"><img src="/static/img/app_store.png" alt="App Store"></a>
            </div> -->
            <div class="small-12 columns">
              <a href="https://play.google.com/store/apps/details?id=com.funplus.fr.galaxystorm"><img src="/static/img/google_play.png" alt="Google Play"></a>
            </div>
            <div class="small-12 columns">
              <a href="https://www.facebook.com/GalaxyStormFunplus"><img src="/static/img/fanpage.png" alt="Facebnook Fanpage"></a>
            </div>
          </div>
        </div><!-- end .buttons -->
      </div>
    </div><!-- end .small-10 -->
  </div>
</div><!-- end .page-header -->

tf/templates/topbar.html
<!-- TOP BAR -->
<!-- <div class="main-nav hide-for-small scroll-container">
  <div class="row">
    <div class="medium-12 columns">
      <nav class="top-bar" data-topbar role="navigation">
        <section class="top-bar-section">
          <ul>
            <li><a href="#"><img src="/static/img/logo.jpg" alt="Logo" width="100"></a></li>
            <li><a class="active" href="#">Home</a></li>
            <li><a href="#">Events</a></li>
            <li><a href="#">Game Info</a></li>
            <li><a href="#">Strategies</a></li>
          </ul>
        </section>
      </nav>
    </div>
  </div>
</div> -->